### PR TITLE
[CR-10147] Fix bug for reporting multiple redis

### PR DESCRIPTION
**Pull request by rbaydoun**
This fixes an issue where only the last redis instance in the list of configured instances in /etc/scollector.toml was being reported on.
Previously closure on the variable was being used when closure on the value is what is important.

Details about this "nuance" can be read here:
https://stackoverflow.com/questions/26692844/captured-closure-for-loop-variable-in-go

### CODE REVIEW

**Comment by gesanderson** [comment]
Shouldn't this PR be merging into the stable branch ? Also, I don't understand why github shows me a 1 line diff when there are 6 commits that modify other code

**Comment by rbaydoun** [comment]
Great concerns Greg, I added a bunch of logging to validate that the code worked, I removed the logging follow that and yes, this is only a single modification required.

On an other note, we pull on this branch for the "configurable_redis" feature to build the scollector container for our shared-redis-cluster.

**Comment by gesanderson** [comment]
Ah, I was not aware you had a modified scollector for your redis cluster. For the future, may I suggest that you rebase your branch and squash any debugging commits ? It gives a simpler commit log and makes it more straightforward for the reviewer.

**Comment by rbaydoun** [comment]
It will be my pleasure, sorry about the messy history.

**Pull request merged**
