### PR TITLE
[PAPI-826] redis plugin to output maxmemory

### PR DESCRIPTION
**Pull request by simon-paradis-jive**
Background: the redis clusters have a {{maxmemory}} (in bytes) configured in /etc/redis.conf, which is templated with gnu m4. The value used is based on a percentage of the actual tug memory limit. 

When this limit is reached, redis is configured to stop accepting writes that would make it use more memory. The purpose is to prevent redis containers from being OOM killed. This worse case situation is better for our purposes.

The actual percentage was determined empirically by injecting data into a test instance with our target tug limit until it blows with an OOM kill. This gives us the {{used_memory}} prior to the oom kill. {{used_memory}} is what redis uses in conjunction with {{maxmemory}}.

We would like to be able to easily graph that maxmemory limit in grafana without editing the graph each time we adjust the tug limit as this requires knowing the internal percentage that's something folks typically forget to update anyway.

This would also allow us to easily create bosun alert without updating them as we change tug memory limits.

### CODE REVIEW

**Comment by simon-paradis-jive** [comment]
extra of `INFO` output the plugin uses:
```
# Memory
used_memory:2821504
used_memory_human:2.69M
used_memory_rss:8929280
used_memory_rss_human:8.52M
used_memory_peak:11686144
used_memory_peak_human:11.14M
used_memory_peak_perc:24.14%
used_memory_overhead:2644346
used_memory_startup:1444856
used_memory_dataset:177158
used_memory_dataset_perc:12.87%
total_system_memory:135146598400
total_system_memory_human:125.87G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:52428800                 <--- This guy
maxmemory_human:50.00M
maxmemory_policy:noeviction
mem_fragmentation_ratio:3.16
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0
```

**Comment by gesanderson** [comment]
Do you want this merged into the official scollector we use for our tug projects ?

**Comment by simon-paradis-jive** [comment]
@gesanderson The scollector used by the redis pods always seemed to be built off `feature/configurable_redis`. Is the "official" scollector including changes from that branch ?

**Comment by gesanderson** [comment]
Looking at the commits in our own branch it doesn't look like we have merged anything from `feature/configurable_redis`. For now your team is pretty much the only one using redis stuff, but if ever we start deploying redis elsewhere it would be worthwhile to have these changes included.

**Comment by simon-paradis-jive** [comment]
Fair enough. I will test these changes in PVU and merge once okay

**Comment by simon-paradis-jive** [comment]
Tested OK in PVU

image

**Pull request merged**
